src/website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from . import db
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash


# Blueprint of auth
auth = Blueprint("auth", __name__)


# Login as a user
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first() # The user to check is the user with this email
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in!", category='success')
                login_user(user, remember=True) # Log in was success
                return redirect(url_for('views.home')) # Redirection to the home page
            else:
                flash("Password is incorrect.", category='error')
        else:
            flash("Email does not exist.", category='error')

    return render_template('login.html', user=current_user) # Print the login html page


# Sign up to the site
@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get("email") # Ask the email
        username = request.form.get("username") # Ask the username
        password1 = request.form.get("password1") # Ask the password
        password2 = request.form.get("password2") # Confirm the password

        email_exists = User.query.filter_by(email=email).first() # Check if the email already exist
        username_exists = User.query.filter_by(username=username).first() # Check if username already exist

        if email_exists:
            flash("Email is already in use.", category='error')
        elif username_exists:
            flash("Username is already in use.", category='error')
        elif password1 != password2:
            flash("Password don\'t match!", category='error')
        elif len(username) < 2:
            flash("Username is too short.", category='error')
        elif len(password1) < 6:
            flash("Password is too short.", category='error')
        elif len(email) < 4:
            flash("Email is invalid.", category='error')
        elif username == 'Admin':
            admin = User(email=email, username=username, password=generate_password_hash(password1, method='sha256'))
            admin.role = 'admin'
            db.session.add(admin)
            db.session.commit()
            login_user(admin, remember=True) # Log in as this user when he was registered
            flash('User created!')
            return redirect(url_for('views.home')) # Redirection to the home page
        else: # In case all is ok
            new_user = User(email=email, username=username, password=generate_password_hash(password1, method='sha256'))
            # New user will have this email, username and password
            db.session.add(new_user) # Add this new user to the database
            db.session.commit() # Refresh the database
            login_user(new_user, remember=True) # Log in as this user when he was registered
            flash('User created!')
            return redirect(url_for('views.home')) # Redirection to the home page

    return render_template('signup.html', user=current_user) # Print the sign-up html page


# Logout
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home')) # Redirection to the home page

src/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from .forms import PostForm
from .models import Post, User, Comment, Like
from . import db


# Blueprint of views
views = Blueprint("views", __name__)


# Home page
@views.route('/')
@views.route('/home')
def home():
    posts = Post.query.all()
    return render_template('home.html', user=current_user, posts=posts)


# Create a post
@views.route('/post/create/public', methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == 'POST':
        text = request.form.get('text')

        if not text: # If the text is empty
            flash("Post cannot be empty", category='error')
        else: # Text available to be upload
            post = Post(text=text, author=current_user.id) # Post will be upload with this text and this author
            db.session.add(post) # Post added to the database
            db.session.commit() # Refresh the database
            flash("Post created!", category='success')
            return redirect(url_for('views.home')) # Redirection to the home page

    return render_template('create_post.html', user=current_user) # Print the create post html page


# Draft post to public post
@views.route('/post/public/<int:post_id>', methods=['GET', 'POST'])
@login_required
def to_public(post_id):
    post = Post.query.get(post_id)
    post.visibility = 'public' # Change visibility of the post
    db.session.commit() # Refresh the database
    flash("Post drafted!", category='success')
        
    return redirect(url_for('views.home')) # Redirection to the home page


# Public post to draft post
@views.route('/post/draft/<int:post_id>', methods=['GET', 'POST'])
@login_required
def to_draft(post_id):
    post = Post.query.get(post_id)
    post.visibility = 'draft' # Change visibility of the post
    db.session.commit() # Refresh the database
    flash("Post drafted!", category='success')
        
    return redirect(url_for('views.home')) # Redirection to the home page
    

# Update a post (unfunctional)
@views.route('/post/update/<int:post_id>', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get(post_id)
    if request.method == 'POST':
        post.text = request.form['text']
        if not post.text: # If the text is empty
            flash("Post cannot be empty", category='error')
        else:
            db.session.commit() # Refresh the database
            flash("Post updated!", category='success')
            return redirect(url_for('views.home')) # Redirection to the home page
        
    return render_template("update_post.html", user=current_user, post=post) # Print the update post html page



# Delete a post
@views.route('/post/delete/<id>')
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first() # The post to check is the post with the id in parameter
    db.session.delete(post) # Post remove from the database
    db.session.commit() # Refresh the database
    flash("Post has been deleted", category='success')
    return redirect(url_for('views.home')) # Redirection to the home page


# User's posts
@views.route('/posts/show/<username>')
def posts(username):
    user = User.query.filter_by(username=username).first() # The user to check is the user with the username in parameter

    if not user:
        flash("No user with that username exists.", category='error')
        return redirect(url_for('views.home')) # Redirection to the home page

    posts = user.posts # Take all the user's posts
    return render_template('posts.html', user=current_user, posts=posts, username=username) # Print the posts html page with his posts


# Show all draft posts
@views.route('/posts/show/draft/<username>')
def posts_draft(username):
    user = User.query.filter_by(username=username).first() # The user to check is the user with the username in parameter

    if not user:
        flash("No user with that username exists.", category='error')
        return redirect(url_for('views.home')) # Redirection to the home page

    posts = user.posts # Take all the user's posts
    return render_template('posts_draft.html', user=current_user, posts=posts, username=username) # Print the posts html page with his posts



# Create a comment in a post
@views.route('/post/create/comment/<post_id>', methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text') # We want a text in the comment section

    if not text:
        flash("Comment cannot be empty.", category='error')
    else:
        post = Post.query.filter_by(id=post_id) # The post to check is the post with the post_id in parameter
        if post:
            comment = Comment(text=text, author=current_user.id, post_id=post_id) # The comment will be with this text, by author, and on this post_id
            db.session.add(comment) # Add the comment to the database
            db.session.commit() # Refresh the database
        else:
            flash("Post does not exist.", category='error')

    return redirect(url_for('views.home')) # Redirection to the home page


# Delete a comment from a post
@views.route('/post/delete/comment/<comment_id>')
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first() # The comment to check is the comment with the comment_id in parameter

    if not comment:
        flash("Comment does not exist.", category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash("You do not have permission to delete this comment.", category='error')
    else:
        db.session.delete(comment) # Delete the comment from the database
        db.session.commit() # Refresh the database

    return redirect(url_for('views.home')) # Redirection to the home page


# Like a post
@views.route('/post/like/<post_id>', methods=['POST'])
@login_required
def like(post_id):
    post = Post.query.filter_by(id=post_id).first() # The post to check is the post with the id in parameter
    like = Like.query.filter_by(author=current_user.id, post_id=post_id).first() # The like will be by this author on this post_id

    if not post:
        return jsonify({'error': "Post does not exist."}, 400) # Error if the post exist
    elif like:
        db.session.delete(like) # Delete the like from the post
        db.session.commit() # Refresh the database
    else:
        like = Like(author=current_user.id, post_id=post_id) # The like will be by this author on this post_id
        db.session.add(like) # Add the like to the post
        db.session.commit() # Refresh the database

    return jsonify({"likes": len(post.likes), "liked": current_user.id in map(lambda x: x.author, post.likes)}) # Communication with JavaScript file

src/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <div class="p-3 mb-2 bg-success text-dark">
    <head>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous"
      />
      <script
        src="https://kit.fontawesome.com/999ca2bb93.js"
        crossorigin="anonymous"
      ></script>
      <title>{% block title %}SpotiNyk{% endblock %}</title>
    </head>
    <body style="background-color: #198754">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{url_for('views.home')}}">
            SpotiNyk
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="/home">Home</a>
              {% if current_user.is_authenticated %} {% if current_user.role ==
              'author' or current_user.role == 'admin' %}
              <a
                class="nav-item nav-link"
                href="{{url_for('views.posts', username=current_user.username)}}"
                >My posts</a
              >
              {% if current_user.role == 'admin' %}
              <a
                class="nav-item nav-link"
                href="{{url_for('users.index', user_id=user.id)}}"
                >Users</a
              >
              {% endif %} {% endif %}
              <ul class="navbar-nav mr-auto me-5 ms-2 mb-md-0">
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    id="navbarDropdown"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    {{current_user.username}}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li>
                      <a
                        class="dropdown-item"
                        href="{{url_for('users.show', user_id=current_user.id)}}"
                        >Info</a
                      >
                    </li>
                    <li>
                      <a class="dropdown-item" href="{{url_for('auth.logout')}}"
                        >Logout</a
                      >
                    </li>
                  </ul>
                </li>
              </ul>
              {% else %}
              <a class="nav-item nav-link" href="/login">Login</a>
              <a class="nav-item nav-link" href="/sign-up">Sign Up</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      <div class="alert alert-danger alter-dismissible fade show" role="alert">
        {{ message }}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
        ></button>
      </div>
      {% else %}
      <div class="alert alert-success alter-dismissible fade show" role="alert">
        {{ message }}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
        ></button>
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %}
      <div class="container">{% block content %}{% endblock %}</div>
      <div class="bottom">
        <footer class="py-3 my-4">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item">
              <a href="/home" style="color: #000000">Home</a>
            </li>
          </ul>
          <p class="text-center" style="color: #000000">© 2022 SpotiNyk</p>
        </footer>
      </div>
      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></script>
      <script
        type="text/javascript"
        src="{{url_for('static', filename='index.js')}}"
      ></script>
    </body>
  </div>
</html>

src/website/templates/create_post.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<br />
<h1 align="center">Make a Post</h1>
<br />
{% if user.role == 'admin' or user.role == 'author' %}
<form method="POST">
  <textarea name="text" id="text" class="form-control"></textarea>
  <br />
  <div align="right">
    <a href="/home"><button type="button" class="btn btn-dark">Back</button></a>
    <button type="submit" class="btn btn-dark">Post</button>
  </div>
</form>
{% else %}
<p>No access for you</p>
{% endif %}
<br />
{% endblock %}

src/website/templates/create_user.html
{% extends "base.html" %}
{% block title %}Create user{% endblock %}
{% block content %}
    <form method="POST">
      <br />
      <h3 align="center">Create user</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="text"
          id="email"
          name="email"
          class="form-control"
          placeholder="Enter Email"
        />
        <br />
        <label for="username">Username</label>
        <input
          type="text"
          id="username"
          name="username"
          class="form-control"
          placeholder="Enter Username"
        />
        <br />
        <label for="password1">Password</label>
        <input
          type="password"
          id="password1"
          name="password1"
          class="form-control"
          placeholder="Enter Password"
        />
        <br />
        <label for="password2">Confirm password</label>
        <input
          type="password"
          id="password2"
          name="password2"
          class="form-control"
          placeholder="Confirm password"
        />
        <br />
        <div align="right">
          <a href="/users/list">
            <button type="button" class="btn btn-dark">Back</button>
          </a>
          <button class="btn btn-dark" type="submit">Create</button>
        </div>
      </div>
    </form>
{% endblock %}
    

src/website/templates/home.html
{% extends "posts_div.html" %}
{% block title %}Home{% endblock %}

src/website/templates/list_users.html
{% extends "base.html" %}
{% block title %}Users list{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <h1 class="mt-5">Users list</h1>
    </div>
    <div class="col text-end">
        <a class="btn btn-dark mt-5" href="{{url_for('users.create')}}">Create user</a>
    </div>
</div>
<br />
<table class="table table-dark table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
     {% for eachUser in user %} 
      <tr>
        <th scope="row">{{eachUser.id}}</th>
        <td class="lead">{{eachUser.username}}</td>
        <td class="lead">{{eachUser.email}}</td>
        <td>
            <form action="{{url_for('users.destroy', user_id=eachUser.id)}}" method="POST">

                <a href="{{url_for('users.show', user_id=eachUser.id)}}"
                    class="btn btn-outline-success"
                    role="button">
                        Show
                </a>
                <a href="{{url_for('users.update', user_id=eachUser.id)}}"
                    class="btn btn-outline-primary"
                    role="button">
                        Edit
                </a>
                <button type="submit"
                    action="{{url_for('users.destroy', user_id=eachUser.id)}}"
                    method="POST"
                    class="btn btn-outline-danger">
                        Delete
                </button>
            </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

src/website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content%}
    <form method="POST">
      <br />
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="text"
          id="email"
          name="email"
          class="form-control"
          placeholder="Enter Email"
        />
        <br />
        <label for="password">Password</label>
        <input
          type="password"
          id="password"
          name="password"
          class="form-control"
          placeholder="Enter Password"
        />
        <br />
        <div align="right">
          <a href="/home">
            <button type="button" class="btn btn-dark">Back</button>
          </a>
          <button class="btn btn-dark" type="submit">Login</button>
        </div>
      </div>
    </form>
{% endblock %}

src/website/templates/posts.html
{% extends "posts_div.html" %}
{% block title %}{{username}}'s public posts{% endblock%}
{% block header %}
    {{username}}'s public posts
    {% if current_user.is_authenticated and (username == user.username or user.role == 'admin')%}
    <div align="right">
        <a href="{{url_for('views.posts_draft', username=username)}}">
        <button type="button" class="btn btn-dark">Draft posts</button>
        </a>
    </div>
    {% endif %}
{% endblock %}
{% block footer %}
    <div align="right">
        <a href="/home">
            <button type="button" class="btn btn-dark">Home</button>
        </a>
    </div>
{% endblock %}

src/website/templates/posts_div.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content%}
    <br />
    <br />
    <h1 align="left">{% block header %}Posts{% endblock %}</h1>
    <br />
    <div id="posts">
      {% for post in posts %}
      {% if post.visibility == 'public' %}
      <div class="shadow p-3 mb-5 bg-dark rounded card border-dark">
        <div class="card-header d-flex justify-content-between align-items-center">
          <a href="/posts/show/{{post.user.username}}" style="color: #ffffff;">{{post.user.username}}</a>
          <div style="color:#ffffff;">
            <span id="likes-count-{{post.id}}">
            {{ post.likes|length }}</span> 
            {% if user.id in post.likes|map(attribute="author")|list %}
            <i
              class="fas fa-thumbs-up"
              id="like-button-{{post.id}}"
              onclick="like({{post.id}})"
            ></i>
            {% else %}
            <i
              class="far fa-thumbs-up"
              id="like-button-{{post.id}}"
              onclick="like({{post.id}})"
            ></i>
            {% endif %}
            {% if user.id == post.author or user.role == 'admin' %}
            <div class="btn-group">
              <button
                type="button"
                class="btn btn-sm btn-success dropdown-toggle"
                data-bs-toggle="dropdown"
              ></button>
              <ul class="dropdown-menu">
                <li>
                  {% if post.visibility == 'public' %}
                    <a href="/post/draft/{{post.id}}" class="dropdown-item">To draft</a>
                  {% else %}
                    <a href="/post/public/{{post.id}}" class="dropdown-item">To public</a>
                  {% endif %}
                  <a href="/post/update/{{post.id}}" class="dropdown-item">Update</a>
                  <a href="/post/delete/{{post.id}}" class="dropdown-item">Delete</a>
                </li>
              </ul>
            </div>
            {% endif %}
          </div>
        </div>
        <div class="card-body bg-dark">
          <div class="card-text" style="color: #ffffff;">{{post.text}}</div>
          <br />
          <div class="collapse" id="comments-{{post.id}}">
            <div class="card">
              <div class="card-body" id="comments-expanded-{{post.id}}">
                {% for comment in post.comments %}
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <a href="/posts/show/{{comment.user.username}}"
                      >{{comment.user.username}}</a
                    >: {{comment.text}}
                  </div>
                  <div>
                    <small class="text-muted"> {{comment.date_created}}</small>
                    {% if user.id == comment.author or user.id == post.author or user.role == 'admin'%}
                    <div class="btn-group">
                      <button
                        type="button"
                        class="btn btn-sm btn-success dropdown-toggle"
                        data-bs-toggle="dropdown"
                      ></button>
                      <ul class="dropdown-menu">
                        <li>
                          <a href="/post/delete/comment/{{comment.id}}" class="dropdown-item">Delete</a>
                        </li>
                      </ul>
                    </div>
                    {% endif %}
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <p class="card-text">
            {% if post.comments|length > 0 %}
            <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
              <small>View {{post.comments|length}} Comments</small>
            </a>
            {% else %}
            <small class="text-muted">No Comments</small>
            {% endif %}
          </p>
          <form
            class="input-group mb-3"
            method="POST"
            action="/post/create/comment/{{post.id}}"
          >
            <input
              type="text"
              id="text"
              name="text"
              class="form-control"
              placeholder="Comment something!"
            />
            <button type="submit" class="btn btn-success">Comment</button>
          </form>
        </div>
          <div class="card-footer text-muted">
            {{post.date_created}}
            <div>
              Post's statut : {{post.visibility}}
            </div>
          </div>
      </div>
      <br/ >
      {% endif %}
      {% endfor %}
    </div>
    {% block footer %}
    {% if current_user.role == 'author' or current_user.role == 'admin' %}
    <div align="right">
      <a href="/post/create/public">
        <button type="button" class="btn btn-dark btn-lg">
          Create a post
        </button>
      </a>
    </div>
    {% endif %}
    {% endblock %}
{% endblock %}
    

src/website/templates/posts_div_draft.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content%}
    <br />
    <br />
    <h1 align="left">{% block header %}Posts{% endblock %}</h1>
    <br />
    <div id="posts">
      {% for post in posts %}
      {% if post.visibility == 'draft' %}
      <div class="shadow p-3 mb-5 bg-dark rounded card border-dark">
        <div class="card-header d-flex justify-content-between align-items-center">
          <a href="/posts/show/{{post.user.username}}" style="color: #ffffff;">{{post.user.username}}</a>
          <div style="color:#ffffff;">
            <span id="likes-count-{{post.id}}">
            {{ post.likes|length }}</span> 
            {% if user.id in post.likes|map(attribute="author")|list %}
            <i
              class="fas fa-thumbs-up"
              id="like-button-{{post.id}}"
              onclick="like({{post.id}})"
            ></i>
            {% else %}
            <i
              class="far fa-thumbs-up"
              id="like-button-{{post.id}}"
              onclick="like({{post.id}})"
            ></i>
            {% endif %}
            {% if user.id == post.author or user.role == 'admin' %}
            <div class="btn-group">
              <button
                type="button"
                class="btn btn-sm btn-success dropdown-toggle"
                data-bs-toggle="dropdown"
              ></button>
              <ul class="dropdown-menu">
                <li>
                  {% if post.visibility == 'public' %}
                    <a href="/post/draft/{{post.id}}" class="dropdown-item">To draft</a>
                  {% else %}
                    <a href="/post/public/{{post.id}}" class="dropdown-item">To public</a>
                  {% endif %}
                  <a href="/post/update/{{post.id}}" class="dropdown-item">Update</a>
                  <a href="/post/delete/{{post.id}}" class="dropdown-item">Delete</a>
                </li>
              </ul>
            </div>
            {% endif %}
          </div>
        </div>
        <div class="card-body bg-dark">
          <div class="card-text" style="color: #ffffff;">{{post.text}}</div>
          <br />
          <div class="collapse" id="comments-{{post.id}}">
            <div class="card">
              <div class="card-body" id="comments-expanded-{{post.id}}">
                {% for comment in post.comments %}
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <a href="/posts/show/{{comment.user.username}}"
                      >{{comment.user.username}}</a
                    >: {{comment.text}}
                  </div>
                  <div>
                    <small class="text-muted"> {{comment.date_created}}</small>
                    {% if user.id == comment.author or user.id == post.author or user.role == 'admin'%}
                    <div class="btn-group">
                      <button
                        type="button"
                        class="btn btn-sm btn-success dropdown-toggle"
                        data-bs-toggle="dropdown"
                      ></button>
                      <ul class="dropdown-menu">
                        <li>
                          <a href="/post/delete/comment/{{comment.id}}" class="dropdown-item">Delete</a>
                        </li>
                      </ul>
                    </div>
                    {% endif %}
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <p class="card-text">
            {% if post.comments|length > 0 %}
            <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
              <small>View {{post.comments|length}} Comments</small>
            </a>
            {% else %}
            <small class="text-muted">No Comments</small>
            {% endif %}
          </p>
          <form
            class="input-group mb-3"
            method="POST"
            action="/post/create/comment/{{post.id}}"
          >
            <input
              type="text"
              id="text"
              name="text"
              class="form-control"
              placeholder="Comment something!"
            />
            <button type="submit" class="btn btn-success">Comment</button>
          </form>
        </div>
        <div class="card-footer text-muted">
          {{post.date_created}}
          <div>
            Post's statut : {{post.visibility}}
          </div>
        </div>
      </div>
      <br/ >
      {% endif %}
      {% endfor %}
    </div>
    {% block footer %}
    {% endblock %}
{% endblock %}
    

src/website/templates/posts_draft.html
{% extends "posts_div_draft.html" %}
{% block title %}{{username}}'s draft posts{% endblock%}
{% block header %}
    {{username}}'s draft posts
    <div align="right">
        <a href="{{url_for('views.posts', username=username)}}">
            <button type="button" class="btn btn-dark">Public posts</button>
        </a>
    </div>
{% endblock %}
{% block footer %}
    <div align="right">
        <a href="/home">
            <button type="button" class="btn btn-dark">Home</button>
        </a>
    </div>
{% endblock %}

src/website/templates/update_post.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content%}
    <br />
    <br />
    <h1 align="center">Update Post</h1>
    
    <form method="POST">
      <br />
      <form action="{{url_for('views.update_post', post_id=post.id)}}" method="POST" enctype="multipart/form-data">
        <div class="mb-3">
            <label for="text" class="form-label"><font size="5pt">Correct your text</font></label>
            <input type="text" name="text" class="form-control" id="inputText" style='height="20px"' value="{{post.text}}"></input>
        </div>
        <div align="right">
          <a href="/home"><button type="button" class="btn btn-dark">Back</button></a>
          <button type="submit" class="btn btn-dark">Update</button>
        </div>
      </form>
    </form>
    <br />
{% endblock %}